name: friends_zone
description: "A new Flutter project for proximity social discovery and voice lounge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  
  # অ্যান্ড্রয়েড ভি২ এম্বেডিং সাপোর্ট করা audioplayers ভার্সন
  audioplayers: ^6.0.0

  # ফায়ারবেসের সামঞ্জস্যপূর্ণ ভার্সনসমূহ
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/friendszone.jpg
