name: friends_zone
description: "A new Flutter project for proximity social discovery and voice lounge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # লোকাল সেট ও ক্যাশ/পেমেন্ট সেভ করার জন্য
  shared_preferences: ^2.2.2

  # আইকন ও ইউজার ইন্টারফেসের জন্য
  cupertino_icons: ^1.0.6

  # ছবি বা ফাইল সিলেক্ট করার জন্য (ফাইল আপলোড-প্রদান ফিচারের জন্য)
  image_picker: ^1.0.7

  # (সাময়িকভাবে বাদ দেওয়া হলো যাতে বিল্ডে সমস্যা না হয়)
  # audioplayers: ^6.0.0

  # ফায়ারবেস ইন্টিগ্রেশনের জন্য (ভবিষ্যত ব্যাকএন্ড প্রজেক্টের)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # অ্যাপের লোগো বা অ্যাসেট ইমেজ রেজিস্ট্রি করার স্থানে
  assets:
    - assets/images/friendszone.jpg
