dependencies:
  flutter:
    sdk: flutter

  # লোকাল সেট ও ক্যাশ সেভ করার জন্য
  shared_preferences: ^2.2.2

  # আইকন ও ইউজার ইন্টারফেসের জন্য
  cupertino_icons: ^1.0.6

  # ছবি বা ফাইল সিলেক্ট করার জন্য
  image_picker: ^1.0.7

  # ভয়েস লাউঞ্জ বা অডিও ফিচারের জন্য
  audioplayers: ^6.0.0

  # ফায়ারবেসের এমন ভার্সন যা flutter 3.19.x এর সাথে কোনো এরর ছাড়াই কাজ করবে
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
